name: classroom-autograde

on:
  push:
  pull_request:

jobs:
  grade:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      # Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Python deps & tests
        working-directory: python
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pytest -q

      # Node (Express)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Node deps & tests
        working-directory: node
        run: |
          npm ci || npm i
          npm test

      # React
      - name: React deps & tests
        working-directory: react
        run: |
          npm ci || npm i
          npm test

      # Score aggregation (simple)
      - name: Aggregate results
        run: echo "All suites executed"
